### PR TITLE
Fix deployment architecture and optimise builds

### PR DESCRIPTION
**Pull request by theadambyrne**
AgriNet python service is a messy solution (still works) this is an experimental branch to simplify and improve the sprawled deployment strategies.

### CODE REVIEW

**Comment by theadambyrne** [comment]
sat_agrinet is ready for test

**Comment by theadambyrne** [comment]
The entire camera service could be ported to bash script.

**Comment by theadambyrne** [comment]
cc @Derv6464

**Comment by theadambyrne** [comment]
`camera` and `agrinet` work on my machine as far as possible.

**Comment by Derv6464** [comment]
This looks good. the results are being written to a file right? should i add to the go to read in that file every x sec for new lines, or could we mess up the file doing this if python and go r messing with it?

**Comment by theadambyrne** [comment]
Can you test this _runs_ ? READMEs have been tidied up for starting/deploying/stopping/debug

**Pull request merged**
